image:
  file: .gitpod.Dockerfile

tasks:
- name: LaTeX auto-rebuild
  command: >
    while find . -name 'resume.tex' | xargs inotifywait -qqre modify .; do         latexmk -pdf ;       done
- name: Terminal